# Using multi-stage builds

# First stage: Build PHP-FPM 
FROM php:8.2-fpm AS php-fpm-stage

# Install necessary PHP extensions
RUN docker-php-ext-install pdo pdo_mysql mysqli
RUN pecl install redis && docker-php-ext-enable redis

# Copy PHP source files into the container
COPY . /var/www/html/

# Command to start PHP-FPM
CMD ["php-fpm"]

# Second stage: Build Nginx
FROM nginx:latest AS nginx-stage

# Copy nginx.ini configuration into the Nginx configuration directory inside the container
COPY nginx.ini /etc/nginx/conf.d/default.conf

# Command to start Nginx
CMD ["nginx", "-g", "daemon off;"]
