--Task 1 - Constraints

--1 Constraint Search 
SELECT OWNER, CONSTRAINT_NAME, TABLE_NAME, 
SEARCH_CONDITION, INDEX_NAME FROM USER_CONSTRAINTS
WHERE TABLE_NAME = ‘CLIENT'
OR TABLE_NAME = ‘EMP'
OR TABLE_NAME = ‘DEPT'
OR TABLE_NAME = ‘PURCHASE'
OR TABLE_NAME = ‘CLIENT';

--2 Constraint Create 
--PurchaseNo Primary Key
ALTER TABLE PURCHASE ADD CONSTRAINT PK_PURCHASENO PRIMARY KEY (PurchaseNo);

--DName Unique 
ALTER TABLE DEPT ADD CONSTRAINT UN_DNAME UNIQUE (DName);

--EName NOT NULL
ALTER TABLE EMP MODIFY EName NOT NULL;

--DName NOT NULL
ALTER TABLE DEPT MODIFY DName NOT NULL;

--CName NOT NULL
ALTER TABLE CLIENT MODIFY CName NOT NULL;

--ReceiptNo NOT NULL
ALTER TABLE PURCHASE MODIFY ReceiptNo NOT NULL;

--Amount CHECK
ALTER TABLE PURCHASE ADD CONSTRAINT CK_AMOUNT
CHECK (Amount > 0);

--Position CHECK
ALTER TABLE EMP ADD CONSTRAINT CK_POSITION
CHECK (Position = 'Group Manager' OR Position= 'Group Assistant' OR Position = 'Group Member' OR Position = 'Team Leader' OR Position = 'Branch Manager');

--ServiceType CHECK
ALTER TABLE PURCHASE ADD CONSTRAINT CK_SERVICETYPE
CHECK (ServiceType = 'Software Installation' OR ServiceType = 'Software Repair' OR ServiceType = 'Training' OR ServiceType = 'Consultation' OR ServiceType = 'Data Recovery');

--PaymentType CHECK
ALTER TABLE PURCHASE ADD CONSTRAINT CK_PAYMENTTYPE
CHECK (PaymentType = 'Debit' OR PaymentType = 'Cash' OR PaymentType = 'Credit');

--GST CHECK
ALTER TABLE PURCHASE ADD CONSTRAINT CK_GST
CHECK (GST = 'Yes' OR GST = 'No');

--DeptNo Foreign Key
ALTER TABLE EMP ADD CONSTRAINT FK_DEPTNO
FOREIGN KEY (DeptNo) REFERENCES DEPT (DeptNo);

--ServedBy Foreign Key
ALTER TABLE PURCHASE ADD CONSTRAINT FK_EMPNO
FOREIGN KEY (ServedBy) REFERENCES EMP (EmpNo);

--ClientNo Foreign Key
ALTER TABLE PURCHASE ADD CONSTRAINT FK_CLIENTNO
FOREIGN KEY (ClientNo) REFERENCES CLIENT (ClientNo);

--Task 2 - Triggers

--1 Sequence PNO_SEQ
CREATE SEQUENCE "PNO_SEQ" MINVALUE 10000 MAXVALUE 99999 
INCREMENT BY 1 START WITH 10000;

--2 Trigger BI_PNO
CREATE OR REPLACE TRIGGER "BI_PNO" 
 BEFORE INSERT ON "PURCHASE" 
 FOR EACH ROW 
BEGIN 
 SELECT "PNO_SEQ".NEXTVAL INTO :NEW.PurchaseNo FROM PURCHASE; 
END; 
/

--3 Trigger TOP_DISCOUNT
CREATE OR REPLACE TRIGGER "TOP_DISCOUNT"
 BEFORE INSERT ON "PURCHASE" 
 FOR EACH ROW 
DECLARE 
 TOP_ClientNo INTEGER;
BEGIN
 SELECT ClientNo
 INTO Top_ClientNo
 FROM (SELECT SUM(Amount), ClientNo
	FROM PURCHASE
	GROUP BY ClientNo
	ORDER BY SUM(Amount) DESC)
 FETCH FIRST 1 ROWS ONLY;
 IF :NEW.ClientNo = TOP_ClientNo THEN
    :NEW.Amount := 0.85 * :NEW.Amount;
 END IF;
END;
/

--4 Trigger SUNSHINE_DEPT
CREATE OR REPLACE TRIGGER "SUNSHINE_DEPT" 
 BEFORE INSERT ON "PURCHASE" 
 FOR EACH ROW 
DECLARE
 DEPT_DeptNo INTEGER;
 EMP_DeptNo INTEGER;
 DEPT_DName VARCHAR(16) := 'SALES - Sunshine';
BEGIN
 SELECT DeptNo INTO DEPT_DeptNo FROM DEPT WHERE DName = DEPT_DName;
 SELECT DeptNo INTO EMP_DeptNo FROM EMP WHERE EmpNo = :NEW.ServedBy;
 IF DEPT_DeptNo = EMP_DeptNo THEN :NEW.PaymentType := 'Cash';
  IF :NEW.ServiceType = 'Data Recovery' THEN :NEW.Amount := 0.7 * :NEW.Amount;
  END IF;
 END IF;
END;
/
